### PR TITLE
fix(source): fix link detection

### LINKED ISSUE #241: 🐛 [Bug] Exisiting Links are broken
With the Rich Text Editor we changed the link rendering. 

That causes existing Links not to be rendered as links anymore

### PR DESCRIPTION
**Pull request by antontranelis**
- [x] fixing existing links detection
- [x] correctly ignoring links like `<test.com>`

fixes #241

### CODE REVIEW

File: src/Components/Map/Subcomponents/ItemPopupComponents/TextView.tsx [hunk 1]
```diff
@@ -53,6 +53,22 @@ export const TextView = ({
...
+        shortUrl = url.split('https://')[1]
+      }
+
+      if (url.match('^http://')) {
+        shortUrl = url.split('http://')[1]
+      }
+
+      return `[${shortUrl}](${url})`
+    })
+  }
```
Comment (ulfgebhardt) [inline src/Components/Map/Subcomponents/ItemPopupComponents/TextView.tsx]:
```suggestion
  if (replacedText) {
    replacedText = replacedText.replace(/(?<!\]?\()(?<!<)https?:\/\/[^\s)]+(?!\))(?!>)/g, (url) => `[${url.replace(/https?:\/\/w{3}\./gi,'')}](${url})`
    })
  }
```

Note: this also replaces the `www`

**Review by ulfgebhardt — APPROVED** [review]
