### PR TITLE
fix(source): select position on index page

### LINKED ISSUE #42: 🚀 [Feature] Add select position to the item menu in index page
Select Position is missing on the index page but available on the map. This can be confusing for users
photo_2024-11-21_09-08-21

### PR DESCRIPTION
**Pull request by antontranelis**
fixes #42

### CODE REVIEW

File: src/Components/Templates/ItemCard.tsx [hunk 1]
```diff
@@ -38,6 +42,11 @@ export const ItemCard = ({
         item={i}
         api={i.layer?.api}
         editCallback={() => navigate('/edit-item/' + i.id)}
+        setPositionCallback={() => {
+          map.closePopup()
+          setSelectPosition(i)
+          navigate('/')
```
Comment (ulfgebhardt) [inline src/Components/Templates/ItemCard.tsx:48]: are you sure you want to do this?

Comment (antontranelis) [reply src/Components/Templates/ItemCard.tsx:48]: Yes, the profile and the popup should be hidden while the user select the position on the map

**Review by ulfgebhardt — DISMISSED** [review]

**Review by ulfgebhardt — APPROVED** [review]
