### PR TITLE
fix(lib): fix user_created reset when updating other users profile marker

### LINKED ISSUE #367: 🐛 [Bug] As Host I can end up with the name and image of a member
## 🐛 Bug
I tried to relocate the Nomad Location of Ulf and then deleted it. Then in the platform I resulted with Ulf name and image as my own. I still resulted logged in with my credentials. 

Image
Image

### PR DESCRIPTION
**Pull request by antontranelis**
When updating other users items as admin, the admin was set as user_created for this item in local state.

fixes #367

### CODE REVIEW

File: lib/src/Components/Map/Subcomponents/ItemFormPopup.tsx [hunk 1]
```diff
@@ -127,14 +127,14 @@ export function ItemFormPopup(props: Props) {
         const itemWithLayer = {
           ...result.data,
           layer: popupForm.layer,
-          user_created: user ?? undefined,
+          user_created: formItem.user_created,
```
Comment (ulfgebhardt) [inline lib/src/Components/Map/Subcomponents/ItemFormPopup.tsx:130]: this should actually be the backend who does this, not the frontend. This has security implications.
Directus offers this capability as  `$CURRENT_USER` as default value.

https://github.com/directus/directus/discussions/11158

**Review by ulfgebhardt — APPROVED** [review]

File: lib/src/Components/Map/Subcomponents/ItemFormPopup.tsx (hunk 1 above)
Comment (antontranelis) [reply lib/src/Components/Map/Subcomponents/ItemFormPopup.tsx:130]: The intention here is to not set the user_created to the current user. Instead we like to keep the user_created as it is. We can not use the response because this only contains the user_created as uuid, but we need an object with the users name for the local state.

Comment (ulfgebhardt) [reply lib/src/Components/Map/Subcomponents/ItemFormPopup.tsx:130]: I understand the problem, but users should not be allowed to transmit this information in the first palce.
